services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-nestjs-ts
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod

